[infra]
infra-vm ansible_host=10.8.30.20
mgmt-vm  ansible_connection=local

[control_plane]
cp01 ansible_host=10.8.30.30 vrrp_priority=150
cp02 ansible_host=10.8.30.31 vrrp_priority=140
cp03 ansible_host=10.8.30.32 vrrp_priority=130

[workers]
worker01 ansible_host=10.8.30.50 vrrp_priority=150
worker02 ansible_host=10.8.30.51 vrrp_priority=140

[k8s_cluster:children]
control_plane
workers

[all_servers:children]
infra
k8s_cluster

[all_servers:vars]
ansible_user=takayama
ansible_ssh_private_key_file=~/.ssh/id_ed25519
